# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b52c340e820d2157741aa7d8d03c80ccf30dba95987d39054336c6253cad4dfcc154c8de1639ccd8beb017ccaf546b69395817ff8f9ac7302fea553bfb4d67c

test:
  secret_key_base: b63dede5580a804c7afc53f98d09bff53ba70cb6f6c5a0debc5d3766020aee8828b5f4623092be81a20c793843d4cb39bbdb0d558587302af74ec9608a981982

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
